"""
Whitelist definitions for the safe expression evaluator.

This module contains only data — AST node whitelists, module function
whitelists, and the safe execution environment. It is separate from
the validation/evaluation logic in safe_eval.py.
"""

import ast
import math
import random

# numpy is optional — silently skip if not installed
try:
    import numpy as np

    _HAS_NUMPY = True
except ImportError:
    _HAS_NUMPY = False

# ==================================================================
# AST node whitelist — only these node types may appear in an expression
# ==================================================================

ALLOWED_NODES = {
    # Literals
    ast.Constant,
    # Binary ops
    ast.BinOp,
    ast.UnaryOp,
    ast.BoolOp,
    ast.Compare,
    # Expression wrappers
    ast.Expression,
    ast.Load,
    ast.Name,
    ast.IfExp,
    # Collections / sequences
    ast.List,
    ast.Tuple,
    ast.Set,
    ast.Dict,
    ast.ListComp,
    ast.SetComp,
    ast.DictComp,
    ast.GeneratorExp,
    # Subscripts / slices
    ast.Subscript,
    ast.Slice,
    # Function calls (further validated against whitelist)
    ast.Call,
    # Comparison operators
    ast.Eq,
    ast.NotEq,
    ast.Lt,
    ast.LtE,
    ast.Gt,
    ast.GtE,
    ast.Is,
    ast.IsNot,
    ast.In,
    ast.NotIn,
    # Boolean operators
    ast.And,
    ast.Or,
    # Binary operators
    ast.Add,
    ast.Sub,
    ast.Mult,
    ast.Div,
    ast.FloorDiv,
    ast.Mod,
    ast.Pow,
    ast.MatMult,  # @ matrix multiplication (numpy)
    ast.LShift,
    ast.RShift,
    ast.BitOr,
    ast.BitXor,
    ast.BitAnd,
    # Unary operators
    ast.USub,
    ast.UAdd,
    ast.Not,
    ast.Invert,
    # Comprehension clauses / keyword args / starred expressions
    ast.comprehension,
    ast.keyword,
    ast.Starred,
    ast.Attribute,
    ast.Lambda,  # anonymous functions (validated recursively in body)
    ast.arguments,  # function arguments container
    ast.arg,  # single function argument
    ast.Return,  # return statement inside lambda body
}

# Backward compatibility with Python 3.7 and below
for _legacy_name in ("NameConstant", "Num", "Str", "Index", "ExtSlice"):
    _legacy_cls = getattr(ast, _legacy_name, None)
    if _legacy_cls is not None:
        ALLOWED_NODES.add(_legacy_cls)


# ==================================================================
# Module function whitelists
# ==================================================================

MATH_FUNCS = {
    # Trigonometric
    "sin",
    "cos",
    "tan",
    "asin",
    "acos",
    "atan",
    "atan2",
    # Hyperbolic
    "sinh",
    "cosh",
    "tanh",
    "asinh",
    "acosh",
    "atanh",
    # Exponential / logarithmic
    "exp",
    "expm1",
    "log",
    "log1p",
    "log2",
    "log10",
    "pow",
    "sqrt",
    "exp2",
    "cbrt",
    # Rounding / remainder
    "ceil",
    "floor",
    "trunc",
    "fmod",
    "fabs",
    "fma",
    "remainder",
    # Angular conversion
    "degrees",
    "radians",
    # Constants
    "pi",
    "e",
    "tau",
    "inf",
    "nan",
    # Miscellaneous
    "gcd",
    "lcm",
    "factorial",
    "perm",
    "comb",
    "isfinite",
    "isinf",
    "isnan",
    "isclose",
    "isqrt",
    "copysign",
    "fsum",
    "sumprod",
    "prod",
    "hypot",
    "dist",
    "erf",
    "erfc",
    "gamma",
    "lgamma",
    "modf",
    "frexp",
    "ldexp",
    "nextafter",
    "ulp",
}

RANDOM_FUNCS = {
    "random",
    "uniform",
    "triangular",
    "betavariate",
    "expovariate",
    "gammavariate",
    "gauss",
    "lognormvariate",
    "normalvariate",
    "vonmisesvariate",
    "paretovariate",
    "weibullvariate",
    "binomialvariate",
    "randint",
    "randrange",
    "randbytes",
    "getrandbits",
    "choice",
    "choices",
    "sample",
    "shuffle",
    "seed",
    "getstate",
    "setstate",
}

NUMPY_FUNCS = {
    # Trigonometric
    "sin",
    "cos",
    "tan",
    "arcsin",
    "arccos",
    "arctan",
    "arctan2",
    "hypot",
    "deg2rad",
    "rad2deg",
    "degrees",
    "radians",
    "unwrap",
    # Hyperbolic
    "sinh",
    "cosh",
    "tanh",
    "arcsinh",
    "arccosh",
    "arctanh",
    # Exponential / logarithmic
    "exp",
    "expm1",
    "exp2",
    "log",
    "log10",
    "log2",
    "log1p",
    # Arithmetic
    "add",
    "subtract",
    "multiply",
    "divide",
    "power",
    "sqrt",
    "square",
    "abs",
    "fabs",
    "sign",
    "negative",
    "positive",
    "reciprocal",
    "mod",
    "fmod",
    "remainder",
    "divmod",
    "absolute",
    # Rounding
    "round",
    "floor",
    "ceil",
    "trunc",
    "rint",
    "fix",
    "around",
    # Statistics
    "mean",
    "median",
    "std",
    "var",
    "average",
    "percentile",
    "quantile",
    "min",
    "max",
    "ptp",
    "sum",
    "prod",
    "cumsum",
    "cumprod",
    "diff",
    "gradient",
    "histogram",
    "histogram2d",
    "histogramdd",
    "corrcoef",
    "cov",
    "cross",
    "trapz",
    # Linear algebra
    "dot",
    "vdot",
    "inner",
    "outer",
    "matmul",
    "tensordot",
    "kron",
    "trace",
    "einsum",
    # Logic
    "all",
    "any",
    "where",
    "argwhere",
    "nonzero",
    "flatnonzero",
    "clip",
    "isclose",
    "allclose",
    "isnan",
    "isinf",
    "isfinite",
    "isreal",
    "iscomplex",
    "real_if_close",
    # Array creation
    "array",
    "zeros",
    "ones",
    "empty",
    "full",
    "eye",
    "identity",
    "arange",
    "linspace",
    "logspace",
    "geomspace",
    "meshgrid",
    "diag",
    "diagflat",
    "tri",
    "tril",
    "triu",
    "vander",
    "fromfunction",
    "fromiter",
    # Array manipulation
    "reshape",
    "ravel",
    "transpose",
    "swapaxes",
    "concatenate",
    "stack",
    "vstack",
    "hstack",
    "dstack",
    "column_stack",
    "split",
    "vsplit",
    "hsplit",
    "dsplit",
    "array_split",
    "tile",
    "repeat",
    "pad",
    "roll",
    "rot90",
    "flip",
    "fliplr",
    "flipud",
    "expand_dims",
    "squeeze",
    "moveaxis",
    "broadcast_to",
    "broadcast_arrays",
    # Sort / search
    "sort",
    "argsort",
    "argmax",
    "argmin",
    "argpartition",
    "searchsorted",
    "unique",
    "bincount",
    "digitize",
    "lexsort",
    "partition",
    "sort_complex",
    # Polynomials
    "poly",
    "polyval",
    "polyfit",
    "polyder",
    "polyint",
    "roots",
    "polyadd",
    "polysub",
    "polymul",
    "polydiv",
    # Constants
    "pi",
    "e",
    "inf",
    "nan",
    "newaxis",
    "euler_gamma",
    # Type / conversion
    "asarray",
    "asanyarray",
    "ascontiguousarray",
    "asmatrix",
    "atleast_1d",
    "atleast_2d",
    "atleast_3d",
    # Complex number ops
    "conj",
    "conjugate",
    "angle",
    "real",
    "imag",
    # Element-wise comparison / logic
    "maximum",
    "minimum",
    "fmax",
    "fmin",
    "logical_and",
    "logical_or",
    "logical_not",
    "logical_xor",
    "greater",
    "less",
    "greater_equal",
    "less_equal",
    "equal",
    "not_equal",
    # Missing common ops
    "interp",
    "copy",
    "nan_to_num",
    "nanmean",
    "nanstd",
    "nansum",
    "nanmin",
    "nanmax",
    "nanmedian",
    "nanvar",
    "nanprod",
    "nanpercentile",
    "nanquantile",
    "nancumsum",
    "nancumprod",
    "nanargmax",
    "nanargmin",
    "count_nonzero",
    "empty_like",
    "zeros_like",
    "ones_like",
    "full_like",
    # Set operations
    "union1d",
    "intersect1d",
    "setdiff1d",
    "setxor1d",
    "isin",
    "unique_all",
    "unique_counts",
    "unique_inverse",
    "unique_values",
    # Short-form trig (numpy convention)
    "acos",
    "asin",
    "atan",
    "atan2",
    "acosh",
    "asinh",
    "atanh",
    # Signal / advanced math
    "convolve",
    "correlate",
    "sinc",
    "cbrt",
    "heaviside",
    "i0",
    "logaddexp",
    "logaddexp2",
    "spacing",
    "signbit",
    "copysign",
    "nextafter",
    "ldexp",
    "frexp",
    "modf",
    "float_power",
    # Array building / indexing
    "block",
    "indices",
    "diag_indices",
    "tril_indices",
    "triu_indices",
    "diag_indices_from",
    "tril_indices_from",
    "triu_indices_from",
    "unravel_index",
    "ravel_multi_index",
    "ix_",
    "fill_diagonal",
    "place",
    "put",
    "put_along_axis",
    "putmask",
    "append",
    "insert",
    "delete",
    "diagonal",
    "compress",
    "extract",
    # Array properties as functions
    "shape",
    "size",
    "ndim",
    # Callback-based (accept lambda/function arguments)
    "apply_along_axis",
    "apply_over_axes",
    "piecewise",
    "select",
    "vectorize",
    "frompyfunc",
    # More array manipulation
    "ediff1d",
    "take",
    "resize",
    "trim_zeros",
    "rollaxis",
    "trapezoid",
    "copyto",
    "broadcast_shapes",
    "histogram_bin_edges",
    "row_stack",
    "matrix_transpose",
    "vecdot",
    "vecmat",
    # Aliases
    "amax",
    "amin",
    "invert",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "bitwise_not",
    "left_shift",
    "right_shift",
    "cumulative_prod",
    "cumulative_sum",
    "true_divide",
    "floor_divide",
    "concat",
    # Window functions
    "hamming",
    "hanning",
    "bartlett",
    "blackman",
    "kaiser",
    # Fourier transforms
    "fft",
    "ifft",
    "rfft",
    "irfft",
    "fft2",
    "ifft2",
    "fftn",
    "ifftn",
    "fftfreq",
    "fftshift",
    "ifftshift",
}

# Submodule whitelists for nested attribute access.
# Keys are dotted paths, values are sets of allowed child attributes.
NUMPY_SUBMODULES = {
    "numpy.fft": {
        "fft",
        "ifft",
        "rfft",
        "irfft",
        "fft2",
        "ifft2",
        "fftn",
        "ifftn",
        "rfft2",
        "irfft2",
        "rfftn",
        "irfftn",
        "hfft",
        "ihfft",
        "fftfreq",
        "rfftfreq",
        "fftshift",
        "ifftshift",
    },
    "numpy.linalg": {
        "det",
        "inv",
        "eig",
        "eigvals",
        "eigvalsh",
        "eigh",
        "norm",
        "matrix_norm",
        "vector_norm",
        "matrix_rank",
        "solve",
        "lstsq",
        "qr",
        "svd",
        "svdvals",
        "cholesky",
        "pinv",
        "tensorinv",
        "tensorsolve",
        "matrix_power",
        "multi_dot",
        "cond",
        "slogdet",
        "cross",
        "diagonal",
        "matmul",
        "outer",
        "trace",
        "tensordot",
        "vecdot",
        "matrix_transpose",
    },
    "numpy.random": {
        # Core generators
        "rand",
        "randn",
        "randint",
        "random",
        "random_integers",
        "random_sample",
        "ranf",
        "sample",
        "choice",
        "shuffle",
        "permutation",
        "bytes",
        # Seed / state
        "seed",
        "get_state",
        "set_state",
        # Continuous distributions
        "normal",
        "standard_normal",
        "uniform",
        "exponential",
        "beta",
        "gamma",
        "standard_gamma",
        "chisquare",
        "f",
        "gumbel",
        "laplace",
        "logistic",
        "lognormal",
        "rayleigh",
        "standard_cauchy",
        "standard_exponential",
        "standard_t",
        "triangular",
        "vonmises",
        "wald",
        "weibull",
        "pareto",
        "power",
        "zipf",
        # Discrete distributions
        "poisson",
        "binomial",
        "geometric",
        "hypergeometric",
        "negative_binomial",
        "noncentral_chisquare",
        "noncentral_f",
        "logseries",
        # Multivariate
        "dirichlet",
        "multinomial",
        "multivariate_normal",
    },
}

# Module-to-alias mapping: np -> numpy, so np.fft.fft is treated as numpy.fft.fft
MODULE_ALIASES = {"np": "numpy"}

# ==================================================================
# Allowed module → functions mapping (used by the validator)
# ==================================================================

ALLOWED_MODULES = {
    "math": MATH_FUNCS,
    "random": RANDOM_FUNCS,
}

if _HAS_NUMPY:
    ALLOWED_MODULES["numpy"] = NUMPY_FUNCS
    ALLOWED_MODULES["np"] = NUMPY_FUNCS  # np alias
    ALLOWED_MODULES.update(NUMPY_SUBMODULES)  # numpy.fft, numpy.linalg, etc.


# ==================================================================
# Safe instance methods / properties on return values
# (e.g., numpy.linspace(0,10,5).tolist(), array.T)
# ==================================================================

SAFE_METHODS = {
    # Conversion
    "tolist",
    "tobytes",
    "astype",
    # Properties (read-only)
    "T",
    "mT",
    "shape",
    "dtype",
    "size",
    "ndim",
    "nbytes",
    "real",
    "imag",
    "flat",
    "itemsize",
    "strides",
    "base",
    "flags",
    "device",
    "data",
    # Methods with functional equivalents
    "copy",
    "flatten",
    "ravel",
    "transpose",
    "reshape",
    "sum",
    "mean",
    "std",
    "var",
    "min",
    "max",
    "argmax",
    "argmin",
    "argsort",
    "round",
    "floor",
    "ceil",
    "clip",
    "conj",
    "conjugate",
    "diagonal",
    "trace",
    "squeeze",
    "repeat",
    "resize",
    "sort",
    "partition",
    "fill",
    "put",
    "take",
    # Missing common ops
    "cumsum",
    "cumprod",
    "prod",
    "all",
    "any",
    "nonzero",
    "item",
    "dot",
    "view",
    "swapaxes",
    "compress",
    "choose",
    "searchsorted",
    "to_device",
    # frombuffer/fromstring are blocked at the numpy-function level
}


# ==================================================================
# Safe built-in functions & constants
# ==================================================================

SAFE_BUILTINS = {
    # Module references (used as values at runtime)
    "math": math,
    "random": random,
    # Built-in constants
    "True": True,
    "False": False,
    "None": None,
    # Safe built-in functions
    "abs": abs,
    "min": min,
    "max": max,
    "sum": sum,
    "round": round,
    "len": len,
    "range": range,
    "int": int,
    "float": float,
    "str": str,
    "bool": bool,
    "list": list,
    "tuple": tuple,
    "dict": dict,
    "set": set,
    "enumerate": enumerate,
    "zip": zip,
    "map": map,
    "filter": filter,
    "sorted": sorted,
    "reversed": reversed,
    "any": any,
    "all": all,
    "chr": chr,
    "ord": ord,
    "hex": hex,
    "oct": oct,
    "bin": bin,
    "divmod": divmod,
    "pow": pow,
}

if _HAS_NUMPY:
    SAFE_BUILTINS["numpy"] = np
    SAFE_BUILTINS["np"] = np
